# Generated by Django 5.2.6 on 2025-10-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active_officer',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'System Administrator'), ('officer', 'Probation Officer'), ('staff', 'Support Staff')], default='officer', max_length=20),
        ),
    ]
