# Generated by Django 5.2.6 on 2025-10-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_active_officer_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='court_jurisdiction',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'System Administrator'), ('officer', 'Probation Officer'), ('staff', 'Support Staff'), ('judge', 'Judge')], default='officer', max_length=20),
        ),
    ]
