# Generated by Django 5.2.6 on 2025-10-16 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0004_alter_case_options_case_case_number_case_court_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('court_type', models.CharField(choices=[('SUPERIOR', 'Superior Court'), ('DISTRICT', 'District Court'), ('JUVENILE', 'Juvenile Court'), ('DRUG', 'Drug Court'), ('FEDERAL', 'Federal Court')], max_length=20)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('clerk_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'courts',
            },
        ),
        migrations.CreateModel(
            name='CourtOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('SENTENCE', 'Sentence'), ('PROBATION', 'Probation Order'), ('TERMINATION', 'Probation Termination'), ('MODIFICATION', 'Order Modification'), ('WARRANT', 'Bench Warrant'), ('OTHER', 'Other')], max_length=20)),
                ('order_date', models.DateField()),
                ('effective_date', models.DateField()),
                ('order_text', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='court_orders/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'court_orders',
            },
        ),
        migrations.CreateModel(
            name='Hearing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hearing_type', models.CharField(choices=[('ARRAIGNMENT', 'Arraignment'), ('PRETRIAL', 'Pre-trial Conference'), ('MOTION', 'Motion Hearing'), ('TRIAL', 'Trial'), ('SENTENCING', 'Sentencing'), ('REVIEW', 'Review Hearing'), ('VIOLATION', 'Violation Hearing')], max_length=20)),
                ('hearing_date', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('outcome', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'hearings',
                'ordering': ['hearing_date'],
            },
        ),
        migrations.CreateModel(
            name='CourtCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=50, unique=True)),
                ('filing_date', models.DateField()),
                ('next_hearing_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('APPEALED', 'Appealed')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courts.court')),
            ],
            options={
                'db_table': 'court_cases',
            },
        ),
    ]
