# Generated by Django 5.2.6 on 2025-10-16 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courts', '0001_initial'),
        ('judges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtcase',
            name='judge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='judges.judge'),
        ),
        migrations.AddField(
            model_name='courtorder',
            name='court_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courts.courtcase'),
        ),
        migrations.AddField(
            model_name='courtorder',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judges.judge'),
        ),
        migrations.AddField(
            model_name='hearing',
            name='court_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courts.courtcase'),
        ),
        migrations.AddField(
            model_name='hearing',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judges.judge'),
        ),
    ]
