# Generated by Django 5.2.6 on 2025-10-02 08:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='opening_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
