# Generated by Django 5.2.6 on 2025-10-02 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_alter_case_opening_date'),
        ('clients', '0004_alter_client_assigned_officer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='clients.client'),
        ),
    ]
