# Generated by Django 5.2.6 on 2025-10-03 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_alter_case_client'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-opening_date']},
        ),
        migrations.AddField(
            model_name='case',
            name='case_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='case',
            name='court_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='court_type',
            field=models.CharField(choices=[('supreme', 'Supreme Court'), ('high', 'High Court'), ('circuit', 'Circuit Court'), ('district', 'District Court'), ('family', 'Family Court'), ('drug', 'Drug Court'), ('juvenile', 'Juvenile Court')], default='circuit', max_length=20),
        ),
        migrations.AddField(
            model_name='case',
            name='is_high_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='case',
            name='next_court_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='presiding_judge',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'judge'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='presiding_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='case',
            name='sentencing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planitem',
            name='requires_judicial_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rehabilitationplan',
            name='judicial_review_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='case',
            name='officer',
            field=models.ForeignKey(limit_choices_to={'user_type': 'officer'}, on_delete=django.db.models.deletion.PROTECT, related_name='officer_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('pending', 'Pending Review'), ('sentenced', 'Sentenced'), ('appealed', 'Appealed')], default='open', max_length=20),
        ),
    ]
