# Generated by Django 5.2.6 on 2025-10-16 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_alter_case_options_case_case_number_case_court_notes_and_more'),
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='court_case',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rehabilitation_case', to='courts.courtcase'),
        ),
    ]
