# Generated by Django 5.2.6 on 2025-10-02 09:52

from django.db import migrations

def set_created_by_for_existing_clients(apps, schema_editor):
    Client = apps.get_model('clients', 'Client')
    User = apps.get_model('users', 'User')
    
    # Get the first available user (usually the superuser)
    default_user = User.objects.first()
    
    if default_user:
        # Update all existing clients that don't have a created_by value
        Client.objects.filter(created_by__isnull=True).update(created_by=default_user)

class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),  # This should match your previous migration
    ]

    operations = [
        migrations.RunPython(set_created_by_for_existing_clients),
    ]
