# Generated by Django 5.2.6 on 2025-10-16 08:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judge_id', models.CharField(max_length=20, unique=True, verbose_name='Judge ID')),
                ('specialization', models.CharField(choices=[('CRIMINAL', 'Criminal Law'), ('FAMILY', 'Family Law'), ('JUVENILE', 'Juvenile Law'), ('DRUG', 'Drug Court'), ('MENTAL_HEALTH', 'Mental Health'), ('VETERANS', 'Veterans Court'), ('TRAFFIC', 'Traffic Court'), ('CIVIL', 'Civil Law')], default='CRIMINAL', max_length=50)),
                ('appointment_date', models.DateField()),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('office_location', models.CharField(blank=True, max_length=200)),
                ('bio', models.TextField(blank=True, verbose_name='Biography')),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('court', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judges', to='courts.court')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='judge_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Judge',
                'verbose_name_plural': 'Judges',
                'db_table': 'judges',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='JudicialLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('leave_type', models.CharField(choices=[('VACATION', 'Vacation'), ('SICK', 'Sick Leave'), ('CONFERENCE', 'Conference'), ('TRAINING', 'Judicial Training'), ('PERSONAL', 'Personal Leave'), ('OTHER', 'Other')], max_length=50)),
                ('reason', models.TextField(blank=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='judges.judge')),
            ],
            options={
                'verbose_name': 'Judicial Leave',
                'verbose_name_plural': 'Judicial Leaves',
                'db_table': 'judicial_leaves',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CourtAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('assignment_type', models.CharField(choices=[('PERMANENT', 'Permanent'), ('TEMPORARY', 'Temporary'), ('VISITING', 'Visiting Judge'), ('SENIOR', 'Senior Status')], default='PERMANENT', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_assignments', to='courts.court')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_assignments', to='judges.judge')),
            ],
            options={
                'verbose_name': 'Court Assignment',
                'verbose_name_plural': 'Court Assignments',
                'db_table': 'court_assignments',
                'ordering': ['-assignment_date'],
                'unique_together': {('judge', 'court', 'assignment_date')},
            },
        ),
    ]
